/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * novaGUI.java
 *
 * Created on 27/06/2011, 22:01:19
 */
package bracoRobotico;

import com.sun.java_cup.internal.runtime.Symbol;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Djam
 */
public class Main extends javax.swing.JFrame {

    ComunicacaoRS232 sc;
    Thread enviaSequencialmente = new Thread(new Runnable() {

        @Override
        public void run() {
            while (chkEnviarRepetidamente.isSelected()) {
                try {
                    // servo 1
                    sc.enviar(0, servoSld1.getValue());
                    Thread.sleep(Integer.valueOf(controleManualSleep.getText()));
                    // servo 2
                    sc.enviar(1, servoSld2.getValue());
                    Thread.sleep(Integer.valueOf(controleManualSleep.getText()));
                    // servo 3
                    sc.enviar(2, servoSld3.getValue());
                    Thread.sleep(Integer.valueOf(controleManualSleep.getText()));
                    // servo 4
                    sc.enviar(3, servoSld4.getValue());
                    Thread.sleep(Integer.valueOf(controleManualSleep.getText()));
                    // servo 5
                    sc.enviar(4, servoSld5.getValue());
                    Thread.sleep(Integer.valueOf(controleManualSleep.getText()));
                    // servo 6
                    sc.enviar(5, servoSld6.getValue());
                    Thread.sleep(Integer.valueOf(controleManualSleep.getText()));
                    // servo 7
                    sc.enviar(6, servoSld7.getValue());
                    Thread.sleep(Integer.valueOf(controleManualSleep.getText()));
                    // servo 7
                    sc.enviar(7, servoSld8.getValue());
                    Thread.sleep(Integer.valueOf(controleManualSleep.getText()));

                } catch (InterruptedException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    });

    public Main() {

        //this.setIconImage(Toolkit.getDefaultToolkit().getImage("icones/Network-32.png"));

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
            e.printStackTrace();
        }

        initComponents();
        sc = new ComunicacaoRS232();
        carregaPortasDisponiveis();
        sc.setPorta(sc.getPortaEscolhida());
        sc.abrirPorta();



        listaMovimentos.setModel(new DefaultListModel());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabControl = new javax.swing.JTabbedPane();
        tabControleManual = new javax.swing.JPanel();
        pnlServo1 = new javax.swing.JPanel();
        servoValor1 = new javax.swing.JTextField();
        lblServoValor1 = new javax.swing.JLabel();
        lblServoAngulo1 = new javax.swing.JLabel();
        servoAngulo1 = new javax.swing.JTextField();
        servoSld1 = new javax.swing.JSlider();
        pnlServo2 = new javax.swing.JPanel();
        servoValor2 = new javax.swing.JTextField();
        lblServoValor2 = new javax.swing.JLabel();
        lblServoAngulo2 = new javax.swing.JLabel();
        servoAngulo2 = new javax.swing.JTextField();
        servoSld2 = new javax.swing.JSlider();
        pnlServo4 = new javax.swing.JPanel();
        servoValor4 = new javax.swing.JTextField();
        lblServoValor4 = new javax.swing.JLabel();
        lblServoAngulo4 = new javax.swing.JLabel();
        servoAngulo4 = new javax.swing.JTextField();
        servoSld4 = new javax.swing.JSlider();
        pnlServo3 = new javax.swing.JPanel();
        servoValor3 = new javax.swing.JTextField();
        lblServoValor3 = new javax.swing.JLabel();
        lblServoAngulo3 = new javax.swing.JLabel();
        servoAngulo3 = new javax.swing.JTextField();
        servoSld3 = new javax.swing.JSlider();
        pnlServo5 = new javax.swing.JPanel();
        servoValor5 = new javax.swing.JTextField();
        lblServoValor5 = new javax.swing.JLabel();
        lblServoAngulo5 = new javax.swing.JLabel();
        servoAngulo5 = new javax.swing.JTextField();
        servoSld5 = new javax.swing.JSlider();
        pnlServo6 = new javax.swing.JPanel();
        servoValor6 = new javax.swing.JTextField();
        lblServoValor6 = new javax.swing.JLabel();
        lblServoAngulo6 = new javax.swing.JLabel();
        servoAngulo6 = new javax.swing.JTextField();
        servoSld6 = new javax.swing.JSlider();
        pnlServo8 = new javax.swing.JPanel();
        servoValor8 = new javax.swing.JTextField();
        lblServoValor8 = new javax.swing.JLabel();
        lblServoAngulo8 = new javax.swing.JLabel();
        servoAngulo8 = new javax.swing.JTextField();
        servoSld8 = new javax.swing.JSlider();
        pnlServo7 = new javax.swing.JPanel();
        servoValor7 = new javax.swing.JTextField();
        lblServoValor7 = new javax.swing.JLabel();
        lblServoAngulo7 = new javax.swing.JLabel();
        servoAngulo7 = new javax.swing.JTextField();
        servoSld7 = new javax.swing.JSlider();
        pnlConfiguracoesControleManual = new javax.swing.JPanel();
        lblMS = new javax.swing.JLabel();
        controleManualSleep = new javax.swing.JTextField();
        lblSleeep = new javax.swing.JLabel();
        chkEnviarRepetidamente = new javax.swing.JCheckBox();
        btnControleManualPosicaoInicial = new javax.swing.JButton();
        tabControleAutomatico = new javax.swing.JPanel();
        btnCarregar = new javax.swing.JButton();
        pathSequencia = new javax.swing.JTextField();
        lblSelecioneASquencia = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        scrollListaMovimentos = new javax.swing.JScrollPane();
        listaMovimentos = new javax.swing.JList();
        btnIniciar = new javax.swing.JButton();
        btnPosicaoInicial = new javax.swing.JButton();
        lblSleep = new javax.swing.JLabel();
        txtSleep = new javax.swing.JTextField();
        lblMS1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmbPorta = new javax.swing.JComboBox();
        lblPorta = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Braço Robotico");

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        pnlServo1.setBorder(javax.swing.BorderFactory.createTitledBorder("Servo Um"));

        servoValor1.setText("128");
        servoValor1.setEnabled(false);

        lblServoValor1.setText("Valor:");

        lblServoAngulo1.setText("Angulo:");

        servoAngulo1.setEnabled(false);

        servoSld1.setMaximum(254);
        servoSld1.setValue(128);
        servoSld1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                servoSld1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlServo1Layout = new javax.swing.GroupLayout(pnlServo1);
        pnlServo1.setLayout(pnlServo1Layout);
        pnlServo1Layout.setHorizontalGroup(
            pnlServo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServo1Layout.createSequentialGroup()
                        .addComponent(lblServoValor1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servoValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblServoAngulo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servoAngulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                    .addComponent(servoSld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlServo1Layout.setVerticalGroup(
            pnlServo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServo1Layout.createSequentialGroup()
                .addGroup(pnlServo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServoValor1)
                    .addComponent(servoValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServoAngulo1)
                    .addComponent(servoAngulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(servoSld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlServo2.setBorder(javax.swing.BorderFactory.createTitledBorder("Servo Dois"));

        servoValor2.setText("128");
        servoValor2.setEnabled(false);

        lblServoValor2.setText("Valor:");

        lblServoAngulo2.setText("Angulo:");

        servoAngulo2.setEnabled(false);

        servoSld2.setMaximum(254);
        servoSld2.setValue(128);
        servoSld2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                servoSld2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlServo2Layout = new javax.swing.GroupLayout(pnlServo2);
        pnlServo2.setLayout(pnlServo2Layout);
        pnlServo2Layout.setHorizontalGroup(
            pnlServo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServo2Layout.createSequentialGroup()
                        .addComponent(lblServoValor2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servoValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblServoAngulo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servoAngulo2, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                    .addComponent(servoSld2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlServo2Layout.setVerticalGroup(
            pnlServo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServo2Layout.createSequentialGroup()
                .addGroup(pnlServo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServoValor2)
                    .addComponent(servoValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServoAngulo2)
                    .addComponent(servoAngulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(servoSld2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlServo4.setBorder(javax.swing.BorderFactory.createTitledBorder("Servo Quatro"));

        servoValor4.setText("111");
        servoValor4.setEnabled(false);

        lblServoValor4.setText("Valor:");

        lblServoAngulo4.setText("Angulo:");

        servoAngulo4.setEnabled(false);

        servoSld4.setMaximum(254);
        servoSld4.setValue(111);
        servoSld4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                servoSld4MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlServo4Layout = new javax.swing.GroupLayout(pnlServo4);
        pnlServo4.setLayout(pnlServo4Layout);
        pnlServo4Layout.setHorizontalGroup(
            pnlServo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServo4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServo4Layout.createSequentialGroup()
                        .addComponent(lblServoValor4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servoValor4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblServoAngulo4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servoAngulo4, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                    .addComponent(servoSld4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlServo4Layout.setVerticalGroup(
            pnlServo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServo4Layout.createSequentialGroup()
                .addGroup(pnlServo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServoValor4)
                    .addComponent(servoValor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServoAngulo4)
                    .addComponent(servoAngulo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(servoSld4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlServo3.setBorder(javax.swing.BorderFactory.createTitledBorder("Servo Três"));

        servoValor3.setText("254");
        servoValor3.setEnabled(false);

        lblServoValor3.setText("Valor:");

        lblServoAngulo3.setText("Angulo:");

        servoAngulo3.setEnabled(false);

        servoSld3.setMaximum(254);
        servoSld3.setValue(254);
        servoSld3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                servoSld3MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlServo3Layout = new javax.swing.GroupLayout(pnlServo3);
        pnlServo3.setLayout(pnlServo3Layout);
        pnlServo3Layout.setHorizontalGroup(
            pnlServo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServo3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServo3Layout.createSequentialGroup()
                        .addComponent(lblServoValor3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servoValor3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblServoAngulo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servoAngulo3, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                    .addComponent(servoSld3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlServo3Layout.setVerticalGroup(
            pnlServo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServo3Layout.createSequentialGroup()
                .addGroup(pnlServo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServoValor3)
                    .addComponent(servoValor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServoAngulo3)
                    .addComponent(servoAngulo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(servoSld3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlServo5.setBorder(javax.swing.BorderFactory.createTitledBorder("Servo Cinco"));

        servoValor5.setText("230");
        servoValor5.setEnabled(false);

        lblServoValor5.setText("Valor:");

        lblServoAngulo5.setText("Angulo:");

        servoAngulo5.setEnabled(false);

        servoSld5.setMaximum(254);
        servoSld5.setValue(230);
        servoSld5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                servoSld5MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlServo5Layout = new javax.swing.GroupLayout(pnlServo5);
        pnlServo5.setLayout(pnlServo5Layout);
        pnlServo5Layout.setHorizontalGroup(
            pnlServo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServo5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServo5Layout.createSequentialGroup()
                        .addComponent(lblServoValor5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servoValor5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblServoAngulo5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servoAngulo5, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                    .addComponent(servoSld5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlServo5Layout.setVerticalGroup(
            pnlServo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServo5Layout.createSequentialGroup()
                .addGroup(pnlServo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServoValor5)
                    .addComponent(servoValor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServoAngulo5)
                    .addComponent(servoAngulo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(servoSld5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlServo6.setBorder(javax.swing.BorderFactory.createTitledBorder("Servo Seis"));

        servoValor6.setText("128");
        servoValor6.setEnabled(false);

        lblServoValor6.setText("Valor:");

        lblServoAngulo6.setText("Angulo:");

        servoAngulo6.setEnabled(false);

        servoSld6.setMaximum(254);
        servoSld6.setValue(128);
        servoSld6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                servoSld6MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlServo6Layout = new javax.swing.GroupLayout(pnlServo6);
        pnlServo6.setLayout(pnlServo6Layout);
        pnlServo6Layout.setHorizontalGroup(
            pnlServo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServo6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServo6Layout.createSequentialGroup()
                        .addComponent(lblServoValor6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servoValor6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblServoAngulo6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servoAngulo6, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                    .addComponent(servoSld6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlServo6Layout.setVerticalGroup(
            pnlServo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServo6Layout.createSequentialGroup()
                .addGroup(pnlServo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServoValor6)
                    .addComponent(servoValor6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServoAngulo6)
                    .addComponent(servoAngulo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(servoSld6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlServo8.setBorder(javax.swing.BorderFactory.createTitledBorder("Servo Oito"));

        servoValor8.setText("128");
        servoValor8.setEnabled(false);

        lblServoValor8.setText("Valor:");

        lblServoAngulo8.setText("Angulo:");

        servoAngulo8.setEnabled(false);

        servoSld8.setMaximum(254);
        servoSld8.setValue(128);
        servoSld8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                servoSld8MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlServo8Layout = new javax.swing.GroupLayout(pnlServo8);
        pnlServo8.setLayout(pnlServo8Layout);
        pnlServo8Layout.setHorizontalGroup(
            pnlServo8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServo8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServo8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServo8Layout.createSequentialGroup()
                        .addComponent(lblServoValor8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servoValor8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblServoAngulo8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servoAngulo8, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                    .addComponent(servoSld8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlServo8Layout.setVerticalGroup(
            pnlServo8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServo8Layout.createSequentialGroup()
                .addGroup(pnlServo8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServoValor8)
                    .addComponent(servoValor8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServoAngulo8)
                    .addComponent(servoAngulo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(servoSld8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlServo7.setBorder(javax.swing.BorderFactory.createTitledBorder("Servo Sete"));

        servoValor7.setText("128");
        servoValor7.setEnabled(false);

        lblServoValor7.setText("Valor:");

        lblServoAngulo7.setText("Angulo:");

        servoAngulo7.setEnabled(false);

        servoSld7.setMaximum(254);
        servoSld7.setValue(128);
        servoSld7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                servoSld7MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlServo7Layout = new javax.swing.GroupLayout(pnlServo7);
        pnlServo7.setLayout(pnlServo7Layout);
        pnlServo7Layout.setHorizontalGroup(
            pnlServo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServo7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServo7Layout.createSequentialGroup()
                        .addComponent(lblServoValor7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servoValor7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblServoAngulo7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servoAngulo7, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                    .addComponent(servoSld7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlServo7Layout.setVerticalGroup(
            pnlServo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServo7Layout.createSequentialGroup()
                .addGroup(pnlServo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServoValor7)
                    .addComponent(servoValor7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServoAngulo7)
                    .addComponent(servoAngulo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(servoSld7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlConfiguracoesControleManual.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMS.setText("ms");

        controleManualSleep.setText("250");

        lblSleeep.setText("Sleep após cada comando de:");

        chkEnviarRepetidamente.setText("Enviar comandos repetidamente em sequência");
        chkEnviarRepetidamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEnviarRepetidamenteActionPerformed(evt);
            }
        });

        btnControleManualPosicaoInicial.setText("Posição inicial");
        btnControleManualPosicaoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControleManualPosicaoInicialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConfiguracoesControleManualLayout = new javax.swing.GroupLayout(pnlConfiguracoesControleManual);
        pnlConfiguracoesControleManual.setLayout(pnlConfiguracoesControleManualLayout);
        pnlConfiguracoesControleManualLayout.setHorizontalGroup(
            pnlConfiguracoesControleManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfiguracoesControleManualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConfiguracoesControleManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkEnviarRepetidamente, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlConfiguracoesControleManualLayout.createSequentialGroup()
                        .addComponent(lblSleeep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(controleManualSleep, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMS)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnControleManualPosicaoInicial)
                .addGap(74, 74, 74))
        );
        pnlConfiguracoesControleManualLayout.setVerticalGroup(
            pnlConfiguracoesControleManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfiguracoesControleManualLayout.createSequentialGroup()
                .addGroup(pnlConfiguracoesControleManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConfiguracoesControleManualLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chkEnviarRepetidamente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlConfiguracoesControleManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSleeep)
                            .addComponent(controleManualSleep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMS)))
                    .addGroup(pnlConfiguracoesControleManualLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnControleManualPosicaoInicial)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabControleManualLayout = new javax.swing.GroupLayout(tabControleManual);
        tabControleManual.setLayout(tabControleManualLayout);
        tabControleManualLayout.setHorizontalGroup(
            tabControleManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabControleManualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabControleManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlConfiguracoesControleManual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tabControleManualLayout.createSequentialGroup()
                        .addGroup(tabControleManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlServo1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlServo3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlServo5, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlServo7, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabControleManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlServo2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlServo4, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlServo6, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlServo8, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        tabControleManualLayout.setVerticalGroup(
            tabControleManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabControleManualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlConfiguracoesControleManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabControleManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlServo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlServo2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabControleManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlServo3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlServo4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabControleManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlServo5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlServo6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabControleManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlServo7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlServo8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tabControl.addTab("Controle Manual", tabControleManual);

        btnCarregar.setText("Carregar");
        btnCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarActionPerformed(evt);
            }
        });

        pathSequencia.setEditable(false);

        lblSelecioneASquencia.setText("Selecione o arquivo contendo a sequência de movimentos a ser executada:");

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        scrollListaMovimentos.setViewportView(listaMovimentos);

        btnIniciar.setText("Iniciar");
        btnIniciar.setEnabled(false);
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnPosicaoInicial.setText("Posição Inicial");
        btnPosicaoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosicaoInicialActionPerformed(evt);
            }
        });

        lblSleep.setText("Sleep após cada comando de:");

        txtSleep.setText("1000");

        lblMS1.setText("ms");

        javax.swing.GroupLayout tabControleAutomaticoLayout = new javax.swing.GroupLayout(tabControleAutomatico);
        tabControleAutomatico.setLayout(tabControleAutomaticoLayout);
        tabControleAutomaticoLayout.setHorizontalGroup(
            tabControleAutomaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabControleAutomaticoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabControleAutomaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollListaMovimentos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addComponent(lblSelecioneASquencia, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabControleAutomaticoLayout.createSequentialGroup()
                        .addComponent(pathSequencia, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabControleAutomaticoLayout.createSequentialGroup()
                        .addComponent(lblSleep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSleep, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMS1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPosicaoInicial)))
                .addContainerGap())
        );
        tabControleAutomaticoLayout.setVerticalGroup(
            tabControleAutomaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabControleAutomaticoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelecioneASquencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabControleAutomaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabControleAutomaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLimpar)
                        .addComponent(btnCarregar))
                    .addComponent(pathSequencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabControleAutomaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabControleAutomaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSleep)
                        .addComponent(txtSleep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMS1))
                    .addGroup(tabControleAutomaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIniciar)
                        .addComponent(btnPosicaoInicial)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollListaMovimentos, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );

        tabControl.addTab("Controle Automático", tabControleAutomatico);

        cmbPorta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPorta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmbPortaMouseReleased(evt);
            }
        });
        cmbPorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPortaActionPerformed(evt);
            }
        });

        lblPorta.setText("Porta:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(lblPorta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPorta))
                .addContainerGap(371, Short.MAX_VALUE))
        );

        tabControl.addTab("Configurações", jPanel2);

        jLabel2.setText("Projeto desenvolvido por:");

        jLabel3.setText("Alen");

        jLabel4.setText("Bruno Francisco");

        jLabel5.setText("Francislei");

        jLabel6.setText("Jonas");

        jLabel7.setText("Natanael");

        jLabel8.setText("Timóteo");

        jLabel9.setText("Ademar");

        jLabel10.setText("Curso:");

        jLabel11.setText("EletroEletrônica - Senai/CETEF - 2010/2011 - Noturno");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        tabControl.addTab("Sobre", jPanel3);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bracoRobotico/icones/fundo_top.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabControl, 0, 0, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addComponent(tabControl, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void servoSld1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servoSld1MouseReleased
        System.out.println("teste");
        servoValor1.setText(String.valueOf(servoSld1.getValue()));
        if (!chkEnviarRepetidamente.isSelected()) {
            sc.enviar(0, servoSld1.getValue());
        }

    }//GEN-LAST:event_servoSld1MouseReleased

    private void servoSld2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servoSld2MouseReleased
        servoValor2.setText(String.valueOf(servoSld2.getValue()));
        if (!chkEnviarRepetidamente.isSelected()) {
            sc.enviar(1, servoSld2.getValue());
        }

    }//GEN-LAST:event_servoSld2MouseReleased

    private void servoSld4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servoSld4MouseReleased
        servoValor4.setText(String.valueOf(servoSld4.getValue()));
        if (!chkEnviarRepetidamente.isSelected()) {
            sc.enviar(3, servoSld4.getValue());
        }

    }//GEN-LAST:event_servoSld4MouseReleased

    private void servoSld3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servoSld3MouseReleased
        servoValor3.setText(String.valueOf(servoSld3.getValue()));
        if (!chkEnviarRepetidamente.isSelected()) {
            sc.enviar(2, servoSld3.getValue());
        }

    }//GEN-LAST:event_servoSld3MouseReleased

    private void servoSld7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servoSld7MouseReleased
        servoValor7.setText(String.valueOf(servoSld7.getValue()));
        if (!chkEnviarRepetidamente.isSelected()) {
            sc.enviar(6, servoSld7.getValue());
        }

    }//GEN-LAST:event_servoSld7MouseReleased

    private void servoSld8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servoSld8MouseReleased
        servoValor8.setText(String.valueOf(servoSld8.getValue()));
        if (!chkEnviarRepetidamente.isSelected()) {
            sc.enviar(7, servoSld8.getValue());
        }

    }//GEN-LAST:event_servoSld8MouseReleased

    private void servoSld6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servoSld6MouseReleased
        servoValor6.setText(String.valueOf(servoSld6.getValue()));
        if (!chkEnviarRepetidamente.isSelected()) {
            sc.enviar(5, servoSld6.getValue());
        }

    }//GEN-LAST:event_servoSld6MouseReleased

    private void servoSld5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servoSld5MouseReleased
        servoValor5.setText(String.valueOf(servoSld5.getValue()));
        if (!chkEnviarRepetidamente.isSelected()) {
            sc.enviar(4, servoSld5.getValue());
        }

    }//GEN-LAST:event_servoSld5MouseReleased

    private void chkEnviarRepetidamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEnviarRepetidamenteActionPerformed

        if (chkEnviarRepetidamente.isSelected()) {
            controleManualSleep.setEnabled(false);
            if (enviaSequencialmente.isAlive()) {
                enviaSequencialmente.resume();
            } else {
                enviaSequencialmente.start();
            }

        } else {
            controleManualSleep.setEnabled(true);
            System.out.println("thread parada");
            enviaSequencialmente.suspend();
        }
    }//GEN-LAST:event_chkEnviarRepetidamenteActionPerformed

    public void carregaPortasDisponiveis() {

        cmbPorta.removeAllItems();

        for (String porta : sc.getPortasDisponiveis()) {
            if (porta.contains("COM")) {
                cmbPorta.addItem(porta);
            }
        }

        cmbPorta.setSelectedItem(sc.getPortaEscolhida().getName());
    }
    private void btnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarActionPerformed
        JFileChooser chooser = new JFileChooser(new File("."));
        chooser.setDialogTitle("Selecione o arquivo contendo a sequência de movimentos a executar.");
        chooser.setFileFilter(new FileNameExtensionFilter(".br", "br"));
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                pathSequencia.setText(chooser.getSelectedFile().getPath());
                lerArquivoMovimentos(pathSequencia.getText(), listaMovimentos);
                btnIniciar.setEnabled(true);

            } catch (Exception ex) {
                System.out.println(ex.getMessage());
                JOptionPane.showMessageDialog(this,
                        "Não foi possível carregar a lista de movimentos.\n\n"
                        + "Verifique se a mesma se encontra no formato abaixo: [motor] posicao - comentario\n\n"
                        + "[1] 80 - Pega a latinha\n"
                        + "[2] 40 - Abre a garra\n"
                        + "[1] 140 - Blablabla\n"
                        + "[3] 225 - Sobe o motor\n"
                        + "[4] 110 - Desce a Alavanca\n"
                        + "[2] 100 - Solta a lata",
                        "Não foi possível carregar a lista de movimentos",
                        JOptionPane.ERROR_MESSAGE);
                pathSequencia.setText("");
            }
        }
}//GEN-LAST:event_btnCarregarActionPerformed

    public void lerArquivoMovimentos(String path, JList lista) throws IOException {

        BufferedReader in = new BufferedReader(new FileReader(path));
        DefaultListModel listaModel = (DefaultListModel) lista.getModel();
        String linha;

        listaModel.clear();

        while (in.ready()) {
            linha = in.readLine();
            listaModel.addElement(linha);
        }

        lista.setModel(listaModel);
        in.close();

    }

    private void btnControleManualPosicaoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControleManualPosicaoInicialActionPerformed
        posicaoInicial();
    }//GEN-LAST:event_btnControleManualPosicaoInicialActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

        DefaultListModel modeloLista = (DefaultListModel) listaMovimentos.getModel();
        modeloLista.clear();
        btnIniciar.setEnabled(false);

    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed

        String[] split;
        int motor, valor;

        btnIniciar.setEnabled(false);
        btnPosicaoInicial.setEnabled(false);
        btnCarregar.setEnabled(false);
        btnLimpar.setEnabled(false);
        txtSleep.setEnabled(false);

        DefaultListModel listaModel = (DefaultListModel) listaMovimentos.getModel();

        listaMovimentos.setSelectedIndex(0);

        for (int i = 0; i < listaModel.getSize(); i++) {

            try {

                listaMovimentos.setSelectedIndex(i);
                split = ((String) listaMovimentos.getSelectedValue()).split(" ");

                motor = Integer.parseInt(String.valueOf(split[0].charAt(1))) - 1;
                valor = Integer.valueOf(split[1]);

                sc.enviar(motor, valor);
                Thread.sleep(Integer.valueOf(txtSleep.getText()));

            } catch (InterruptedException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }


        }

        btnIniciar.setEnabled(true);
        btnPosicaoInicial.setEnabled(true);
        btnCarregar.setEnabled(true);
        btnLimpar.setEnabled(true);
        txtSleep.setEnabled(true);


    }//GEN-LAST:event_btnIniciarActionPerformed

    public void posicaoInicial() {
        try {

            servoSld1.setValue(128);
            servoValor1.setText("128");
            servoSld2.setValue(128);
            servoValor1.setText("128");
            servoSld3.setValue(254);
            servoValor1.setText("254");
            servoSld4.setValue(111);
            servoValor1.setText("111");
            servoSld5.setValue(230);
            servoValor1.setText("230");
            servoSld6.setValue(128);
            servoValor1.setText("128");
            servoSld7.setValue(128);
            servoValor1.setText("128");
            servoSld8.setValue(128);
            servoValor1.setText("128");

            // servo 1
            sc.enviar(0, servoSld1.getValue());
            Thread.sleep(1000);
            // servo 2
            sc.enviar(1, servoSld2.getValue());
            Thread.sleep(1000);
            // servo 3
            sc.enviar(2, servoSld3.getValue());
            Thread.sleep(1000);
            // servo 4
            sc.enviar(3, servoSld4.getValue());
            Thread.sleep(1000);
            // servo 5
            sc.enviar(4, servoSld5.getValue());
            Thread.sleep(1000);
            // servo 6
            sc.enviar(5, servoSld6.getValue());
            Thread.sleep(1000);
            // servo 7
            sc.enviar(6, servoSld7.getValue());
            Thread.sleep(1000);
            // servo 7
            sc.enviar(7, servoSld8.getValue());
            Thread.sleep(1000);

        } catch (InterruptedException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btnPosicaoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosicaoInicialActionPerformed
        posicaoInicial();
    }//GEN-LAST:event_btnPosicaoInicialActionPerformed

    private void cmbPortaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbPortaMouseReleased
    }//GEN-LAST:event_cmbPortaMouseReleased

    private void cmbPortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPortaActionPerformed
        if (sc.getPortaEscolhida().isCurrentlyOwned()) {
            sc.fecharPorta();
            System.out.println("Porta fechada: " + sc.getPortaEscolhida().getName());
            sc.setPorta((String) cmbPorta.getSelectedItem());
            System.out.println("Porta setada: " + (String) cmbPorta.getSelectedItem());
            sc.abrirPorta();
            System.out.println("Porta aberta: " + sc.getPortaEscolhida().getName());
        }

    }//GEN-LAST:event_cmbPortaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarregar;
    private javax.swing.JButton btnControleManualPosicaoInicial;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPosicaoInicial;
    private javax.swing.JCheckBox chkEnviarRepetidamente;
    private javax.swing.JComboBox cmbPorta;
    private javax.swing.JTextField controleManualSleep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblMS;
    private javax.swing.JLabel lblMS1;
    private javax.swing.JLabel lblPorta;
    private javax.swing.JLabel lblSelecioneASquencia;
    private javax.swing.JLabel lblServoAngulo1;
    private javax.swing.JLabel lblServoAngulo2;
    private javax.swing.JLabel lblServoAngulo3;
    private javax.swing.JLabel lblServoAngulo4;
    private javax.swing.JLabel lblServoAngulo5;
    private javax.swing.JLabel lblServoAngulo6;
    private javax.swing.JLabel lblServoAngulo7;
    private javax.swing.JLabel lblServoAngulo8;
    private javax.swing.JLabel lblServoValor1;
    private javax.swing.JLabel lblServoValor2;
    private javax.swing.JLabel lblServoValor3;
    private javax.swing.JLabel lblServoValor4;
    private javax.swing.JLabel lblServoValor5;
    private javax.swing.JLabel lblServoValor6;
    private javax.swing.JLabel lblServoValor7;
    private javax.swing.JLabel lblServoValor8;
    private javax.swing.JLabel lblSleeep;
    private javax.swing.JLabel lblSleep;
    private javax.swing.JList listaMovimentos;
    private javax.swing.JTextField pathSequencia;
    private javax.swing.JPanel pnlConfiguracoesControleManual;
    private javax.swing.JPanel pnlServo1;
    private javax.swing.JPanel pnlServo2;
    private javax.swing.JPanel pnlServo3;
    private javax.swing.JPanel pnlServo4;
    private javax.swing.JPanel pnlServo5;
    private javax.swing.JPanel pnlServo6;
    private javax.swing.JPanel pnlServo7;
    private javax.swing.JPanel pnlServo8;
    private javax.swing.JScrollPane scrollListaMovimentos;
    private javax.swing.JTextField servoAngulo1;
    private javax.swing.JTextField servoAngulo2;
    private javax.swing.JTextField servoAngulo3;
    private javax.swing.JTextField servoAngulo4;
    private javax.swing.JTextField servoAngulo5;
    private javax.swing.JTextField servoAngulo6;
    private javax.swing.JTextField servoAngulo7;
    private javax.swing.JTextField servoAngulo8;
    private javax.swing.JSlider servoSld1;
    private javax.swing.JSlider servoSld2;
    private javax.swing.JSlider servoSld3;
    private javax.swing.JSlider servoSld4;
    private javax.swing.JSlider servoSld5;
    private javax.swing.JSlider servoSld6;
    private javax.swing.JSlider servoSld7;
    private javax.swing.JSlider servoSld8;
    private javax.swing.JTextField servoValor1;
    private javax.swing.JTextField servoValor2;
    private javax.swing.JTextField servoValor3;
    private javax.swing.JTextField servoValor4;
    private javax.swing.JTextField servoValor5;
    private javax.swing.JTextField servoValor6;
    private javax.swing.JTextField servoValor7;
    private javax.swing.JTextField servoValor8;
    private javax.swing.JTabbedPane tabControl;
    private javax.swing.JPanel tabControleAutomatico;
    private javax.swing.JPanel tabControleManual;
    private javax.swing.JTextField txtSleep;
    // End of variables declaration//GEN-END:variables
}
